import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";

const AlbertSans = Albert_Sans({
	variable: "--font-albert-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta name="apple-mobile-web-app-title" content="Carrhae Capital" />
				<link
					href="https://fastly-cloud.typenetwork.com/projects/8622/fontface.css?6821d4df"
					rel="stylesheet"
					type="text/css"
				></link>
			</head>
			<body className={`${AlbertSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
